# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_LibSample', [dirname(__file__)])
        except ImportError:
            import _LibSample
            return _LibSample
        if fp is not None:
            try:
                _mod = imp.load_module('_LibSample', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _LibSample = swig_import_helper()
    del swig_import_helper
else:
    import _LibSample
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def new_intp():
  return _LibSample.new_intp()
new_intp = _LibSample.new_intp

def copy_intp(*args):
  return _LibSample.copy_intp(*args)
copy_intp = _LibSample.copy_intp

def delete_intp(*args):
  return _LibSample.delete_intp(*args)
delete_intp = _LibSample.delete_intp

def intp_assign(*args):
  return _LibSample.intp_assign(*args)
intp_assign = _LibSample.intp_assign

def intp_value(*args):
  return _LibSample.intp_value(*args)
intp_value = _LibSample.intp_value
class _node(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, _node, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, _node, name)
    __repr__ = _swig_repr
    __swig_setmethods__["data"] = _LibSample._node_data_set
    __swig_getmethods__["data"] = _LibSample._node_data_get
    if _newclass:data = _swig_property(_LibSample._node_data_get, _LibSample._node_data_set)
    __swig_setmethods__["next"] = _LibSample._node_next_set
    __swig_getmethods__["next"] = _LibSample._node_next_get
    if _newclass:next = _swig_property(_LibSample._node_next_get, _LibSample._node_next_set)
    def __init__(self): 
        this = _LibSample.new__node()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _LibSample.delete__node
    __del__ = lambda self : None;
_node_swigregister = _LibSample._node_swigregister
_node_swigregister(_node)


def list_new():
  return _LibSample.list_new()
list_new = _LibSample.list_new

def list_free(*args):
  return _LibSample.list_free(*args)
list_free = _LibSample.list_free

def list_insert(*args):
  return _LibSample.list_insert(*args)
list_insert = _LibSample.list_insert

def list_next(*args):
  return _LibSample.list_next(*args)
list_next = _LibSample.list_next

def list_node_getint(*args):
  return _LibSample.list_node_getint(*args)
list_node_getint = _LibSample.list_node_getint

def smpl_sum(*args):
  return _LibSample.smpl_sum(*args)
smpl_sum = _LibSample.smpl_sum

def smpl_sub(*args):
  return _LibSample.smpl_sub(*args)
smpl_sub = _LibSample.smpl_sub
# This file is compatible with both classic and new-style classes.


