# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package LibSample;
use base qw(Exporter);
use base qw(DynaLoader);
package LibSamplec;
bootstrap LibSample;
package LibSample;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package LibSample;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package LibSample;

*new_intp = *LibSamplec::new_intp;
*copy_intp = *LibSamplec::copy_intp;
*delete_intp = *LibSamplec::delete_intp;
*intp_assign = *LibSamplec::intp_assign;
*intp_value = *LibSamplec::intp_value;
*list_new = *LibSamplec::list_new;
*list_free = *LibSamplec::list_free;
*list_insert = *LibSamplec::list_insert;
*list_next = *LibSamplec::list_next;
*list_node_getint = *LibSamplec::list_node_getint;
*smpl_sum = *LibSamplec::smpl_sum;
*smpl_sub = *LibSamplec::smpl_sub;

############# Class : LibSample::_node ##############

package LibSample::_node;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( LibSample );
%OWNER = ();
%ITERATORS = ();
*swig_data_get = *LibSamplec::_node_data_get;
*swig_data_set = *LibSamplec::_node_data_set;
*swig_next_get = *LibSamplec::_node_next_get;
*swig_next_set = *LibSamplec::_node_next_set;
sub new {
    my $pkg = shift;
    my $self = LibSamplec::new__node(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        LibSamplec::delete__node($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


# ------- VARIABLE STUBS --------

package LibSample;

1;
